### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by arpitgold** [allure-framework/allure-jenkins-plugin#49]
Its been long time that there is an release. I seen a lot of new features and improvement happened in the code. 
When is the next release planned ?
Eagerly waiting to taste your new official recipes. :smile:

**Comment by arpitgold** [comment]
Any updates ??

**Comment by gabyshev** [comment]
+1

**Comment by mavlyutov** [comment]
released 29.01.2015
see https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin
gimme a few moments to update changelog
