### ISSUE TITLE
Сепарация отчетов в MultiJob

### ISSUE THREAD

**Issue by sergeychipiga** [allure-framework/allure-jenkins-plugin#8]
На текущий момент allure собирает отчеты с динамически генерируемых конфигураций в MultiJob, однако внутри отчета нет сепарации по конфигурациям. Тест-кейсы свалены в кучу - неясно, какой конфигурации принадлежат какие тест-кейсы. Пожалуйста добавьте разделение по конфигурациям

**Comment by baev** [comment]
moved to https://github.com/allure-framework/allure-core/issues/602
